# Generated by Django 4.2.30 on 2026-07-26 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ricambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('codice', models.CharField(max_length=50, unique=True)),
                ('prezzo_unitario', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Veicolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('targa', models.CharField(max_length=10, unique=True)),
                ('modello', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('auto', 'Automobile'), ('agricolo', 'Macchina agricola'), ('camper', 'Camper')], default='auto', max_length=20)),
                ('km_totali', models.PositiveIntegerField(default=0)),
                ('data_immatricolazione', models.DateField(blank=True, null=True)),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('proprietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veicoli', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Intervento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('descrizione', models.TextField()),
                ('km_al_momento', models.PositiveIntegerField()),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('stato', models.CharField(choices=[('programmato', 'Programmato'), ('in_corso', 'In corso'), ('completato', 'Completato')], default='programmato', max_length=20)),
                ('meccanico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interventi_eseguiti', to=settings.AUTH_USER_MODEL)),
                ('ricambi_usati', models.ManyToManyField(blank=True, related_name='interventi', to='manutenzioni.ricambio')),
                ('veicolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventi', to='manutenzioni.veicolo')),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
    ]
