# Generated by Django 4.2.30 on 2026-07-27 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manutenzioni', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='intervento',
            options={'ordering': ['-data'], 'verbose_name': 'Intervento', 'verbose_name_plural': 'Interventi'},
        ),
        migrations.AlterModelOptions(
            name='ricambio',
            options={'ordering': ['nome'], 'verbose_name': 'Ricambio', 'verbose_name_plural': 'Ricambi'},
        ),
        migrations.AlterModelOptions(
            name='veicolo',
            options={'ordering': ['marca', 'modello', 'targa'], 'verbose_name': 'Veicolo', 'verbose_name_plural': 'Veicoli'},
        ),
    ]
